version: '3'

services:
  nextjs:
    image: nextjs:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certs
    depends_on:
      - nextjs
    restart: unless-stopped

volumes:
  certs: