apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf-volume
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./nginx-conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-conf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi