import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Navbar } from '../components/navbar'
import { Cover } from '../components/cover'
import { About } from '../components/about'
import { Projects } from '../components/projects'
import { Contact } from '../components/contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>srinath.tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Navbar />
        <div className='w-screen min-hh-[calc(100vh-78px)] bg-toronto bg-no-repeat bg-cover bg-center'>
          <div className='bg-black/95 bg-cover w-screen h-[calc(100vh-78px)]'>
            <Cover />
          </div>
        </div>
        <About />
        <Projects />
        <Contact />


      
    </>
  )
}
