name: Site Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  nextjs-build:
    name: Next.js Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
  docker-build:
    needs: nextjs-build
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t ${{ secrets.REGISTRY_HOST }}/srinath-tech:${{ env.PR_NUMBER || 'latest' }} .
  helm-build:
    name: Helm Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm Lint
        run: helm lint helm
      - name: Helm Package
        run: helm package helm