name: Website build test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build .