name: Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v2.1, etc.
  release:
    types: [published]

jobs:
  release-build:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Build Docker Image
        run: docker build -t ${{ secrets.REGISTRY_URL }}/srinath-tech:latest .
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.REGISTRY_URL }}/srinath-tech:latest